# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: leantime
stringData:
    LEAN_DB_HOST: ENC[AES256_GCM,data:wv3qI4MxgH1+mJW1GzamQAgIkeQBzxhdysoS1c5hCOWud/Oh2hnDYBc1u6M=,iv:pMkxMHLmwylSG8o4mgsdG5y+beaaes5etbIGFyFh5/8=,tag:9QqGgHbTRjMZH9Z8V6KfUw==,type:str]
    LEAN_DB_USER: ENC[AES256_GCM,data:y0QQ4es6sv4=,iv:zax4IeAQFr1am0a8v5n+bADyjZ6dqrUTby4xonHo4gs=,tag:aKWnWf3rdpnvhMjJ/z/xng==,type:str]
    LEAN_DB_PASSWORD: ENC[AES256_GCM,data:+fUqbMcGOXF2jpMqEE4=,iv:bgPghqgTzzdRVl8HxrTvxrHaqnGSNsLUAUnVr6sgjwM=,tag:hK8gBeVD3YPkHnILkHGbVQ==,type:str]
    LEAN_DB_DATABASE: ENC[AES256_GCM,data:fz+jZxRkYxk=,iv:gz4CIjejdycg+ewmoBEVh7W1wfPxa2cr1gSTry6fZsk=,tag:ODTETj+fs/+knZGhlUDNXg==,type:str]
    LEAN_DB_PORT: ENC[AES256_GCM,data:MmrsVA==,iv:QkkEx0X3dXGKsKoj9PhyyXM5jrZTpwNS/pwYDwuVD/k=,tag:UqnNf2tVEJOLGfMC+7PR8w==,type:str]
    LEAN_SITENAME: ENC[AES256_GCM,data:YRNQEfwoUCpTG82SOv28,iv:n+1oNzoa4MtBf7YVWNStOR19WUYBtHh+AUOJXxI0Jc0=,tag:P0lMuBxnK2X5c4DVZ3dmzw==,type:str]
    LEAN_LANGUAGE: ENC[AES256_GCM,data:JkMFMgM=,iv:DrAxL0eY6ldGLLLi2J8kBbnRf807GnhOZGtOEwB8uj8=,tag:hKSgQO4bG2Kt9AGo0TF8fA==,type:str]
    LEAN_DEFAULT_TIMEZONE: ENC[AES256_GCM,data:3WNEKcPx9VlTsCyMP7v2ug==,iv:4Ug/3VX+w1NenZofN7JQ9CpcrFKAiwudGiEN3la5+tE=,tag:aklvbytFFVOQtsN7wNf/MA==,type:str]
    LEAN_SESSION_PASSWORD: ENC[AES256_GCM,data:KN9WkQOgR8bEGiqdxeON1e0r2AoQ3D4MgEehofgDorOhfUOKppaMW11ydtpixAhw,iv:Bu8VogqnSi9Uauvj2aVSrqxGu+XnjTTI+9JgKitU7V8=,tag:decEglAayg+a2MUb9QExOg==,type:str]
    LEAN_USE_S3: ENC[AES256_GCM,data:IUvv3g==,iv:cP6P6CDWrLo8wUtGS3x8oz61ifKNKYY/onhi+Eojv8c=,tag:ReEP726uZQqU+KUD6U/6qg==,type:str]
    LEAN_S3_KEY: ENC[AES256_GCM,data:/O/CoivFs4ZjdU/vGk2hZbxNKgw=,iv:cbvAqF6GJkqohTmp62dOXHstPcT77JuNmH4lHZoqVdc=,tag:ASpb2dvOOK6XMyFyqHhz9A==,type:str]
    LEAN_S3_SECRET: ENC[AES256_GCM,data:VgGBw+zc5nESw54ARFUa27E810AfXJaQ0Lzx9dszYwdXhol9erXL8A==,iv:HTwk/W3TgYrkCcuqoBzQTpe4va0ufGHGKxU2WroeBeo=,tag:Lxr8COCKRJvNTYmwOLw/tg==,type:str]
    LEAN_S3_BUCKET: ENC[AES256_GCM,data:LwCWsqzdhBE=,iv:ZQckFYu9lJNyGmrxWgStW3zW3JTwFmXX0dESHuJP9uw=,tag:CWPU0rEDvndrIA/h7PyM0w==,type:str]
    LEAN_S3_USE_PATH_STYLE_ENDPOINT: ENC[AES256_GCM,data:A2pg0w==,iv:7DjrpQhnIkIYhIfcYmg48n9CUj2MO2mAoHjzpYF/QFs=,tag:FjaCeET829WgML7Kv/2M7A==,type:str]
    #ENC[AES256_GCM,data:7hJdDX0t69zBtH+GsxFJIhEqpg==,iv:agNiJBQcSAxJTwkyJiCGGzNa4hoVZcR/8rTrPcwoyYY=,tag:dasrwvXVNGjektTgSAtjew==,type:comment]
    #ENC[AES256_GCM,data:gRWlqxo12Cz3XDnDcQeoz+mR/MJ/Lv0T,iv:bN0BllM3d+NIjU4Uhjngiz02T7dajGfjM4IszYOfrms=,tag:XRrfKgrPusmGMj50Z9LPtA==,type:comment]
    LEAN_S3_END_POINT: ENC[AES256_GCM,data:VDCamBrbO4bbspAI5y2D+n1gUkuDszCe,iv:EZqT8T3zaxrH7KB6MfQN093XFvmmn02muCEpBfV6+JE=,tag:jjqbAvM0Gso1lGSKt4jyCw==,type:str]
    LEAN_EMAIL_RETURN: ENC[AES256_GCM,data:ee7J8vGQlN6UcYYQ0zv2nv4=,iv:GtarkB4DOjnERs3K1lDVTdtddHdMCrfB1sObCD0VDF0=,tag:SV0Yf1jqD/gjhkm4cEJVzg==,type:str]
    LEAN_EMAIL_USE_SMTP: ENC[AES256_GCM,data:z2+/zg==,iv:4eQ/kiLj9YUKMPK9rIa1w7iOsPY5dtz2M13CxWpRAj4=,tag:nE5w5kd8k7sKKzwychfEsw==,type:str]
    LEAN_EMAIL_SMTP_HOSTS: ENC[AES256_GCM,data:1TvHzHA3CCj7uCXxdPX9Hms=,iv:eegUK15At2cbUsg0fJtZ44+qjMf+xykVfq7e+WPAu6k=,tag:65iUbi6z37wGF885Rkbd9Q==,type:str]
    LEAN_EMAIL_SMTP_AUTH: ENC[AES256_GCM,data:zAyczw==,iv:WBpiy959j5eKVa5PUGHiJBkTD/sFvm51GhkVL0dv6bg=,tag:BfcTnwJxFTwnE4ddzgIzhw==,type:str]
    LEAN_EMAIL_SMTP_USERNAME: ENC[AES256_GCM,data:WdUc2nKY,iv:i+bg+7vl7/I3n26saiOYtq1XKhQreK2aSwsaZZ3a96M=,tag:Rs4KBx7nkPuBK+fPWK5RSQ==,type:str]
    LEAN_EMAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:otRcsTbP31A3asnn3LKfPCGr53ot+Q5Bsg5D7/TMoewyxqHRHTZwlii9Fg6D7Syqk/UobHrlHAAqcYZC80G7s7+Q6XLS,iv:Ny915xNxQsBTQFTrEqHQ4uS05rVcGnQfb/SMnlzs4Lk=,tag:c4LcW0qXyRhPWMkTcIYyqg==,type:str]
    LEAN_EMAIL_SMTP_AUTO_TLS: ENC[AES256_GCM,data:9nKYvA==,iv:B9BsfX6IRC0TtqhVVPsddRdgOPhDGgPT4ooaczaanZU=,tag:GBmGkV8lMzomDChIrPMkag==,type:str]
    LEAN_EMAIL_SMTP_SECURE: ENC[AES256_GCM,data:PAMM,iv:+x9PFbahiuyshd3xh1EbKH+HIZWqLA+oRjfflOWTBVs=,tag:MoUmInNrg4BVdFyugJ62rQ==,type:str]
    LEAN_EMAIL_SMTP_SSLNOVERIFY: ENC[AES256_GCM,data:gKShfE8=,iv:lvYrD2BKBfPxwF6+bXgz3Jt9ytyRlxjyntnuu8YO/ck=,tag:qHliA3DwDGEwrTK7PJhsHw==,type:str]
    LEAN_EMAIL_SMTP_PORT: ENC[AES256_GCM,data:3CyF,iv:M9YdEHgf/QRCwsoubZq3gNAhqIQVOJSXYMlNPaNAj5E=,tag:Ipt6AMFFJA4hnDdSm0oheg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T05:30:40Z"
    mac: ENC[AES256_GCM,data:8iOFpqfIfXe35oCpKip2nCk4OCgVenL9Q+62h/tH5/nv3jxQZDrpjvrqTBj96g88fxBNzz7QlOzebXoD2fhMvTBxlauVRTbmKOgtp4LyLkJiLDi546m837tEDL6tZOm/EdhzRkiIWwU6OmWS6Zg0FkPo0ypFfq4JVqeLunG7cuA=,iv:YF32kVaOqQjbIhZtCp5rdas+fnRYNzg/SWp55EQIzYk=,tag:JfBs4ETxF2csaPMjl00W0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
