---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./secrets.sops.yaml
  - ./cluster.yaml
  - ./cluster.yaml
  - ./scheduledbackup.yaml
  - ./gatus.yaml
