---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seafile-db
  namespace: seafile
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initdbScripts:
      create_onlyoffice_db.sql: |
        -- Create a new database
        CREATE DATABASE onlyoffice;

        -- Create a new user and set a password
        CREATE USER 'onlyoffice'@'localhost' IDENTIFIED BY '${ONLYOFFICE_DB_PASSWORD}';

        -- Grant privileges to the user on the database
        GRANT ALL PRIVILEGES ON onlyoffice.* TO 'onlyoffice'@'localhost';

        -- Flush privileges
        FLUSH PRIVILEGES;

    auth:
      username: seafile
      existingSecret: app-secrets
    primary:
      extraEnvVars:
        ONLYOFFICE_DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: onlyoffice-db-password
      podSecurityContext:
        fsGroup: 65534
      containerSecurityContext:
        runAsUser: 65534
        runAsGroup: 0
      persistence:
        enabled: true
        storageClass: home-cluster-nfs-1
        size: 5Gi
