apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sSt0pmUd+Sxeb6ObqJKYcfks,iv:SXjN2/nom84ycT2YzfP6QU/9NsAij14Xd5QN+Huj5HU=,tag:Le7RoNZ4wFVkqSOFvHuHWw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vLIyHLi5RabaHedHK5uE0HAltbNfFiqBmXotCm2Rgy0yNqi7,iv:AQBf84F0EzrlH3QQffS0gWA8gWCsnicgO5gk6TzykZo=,tag:GbUFzvG5YaumYtt0L++IYw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NShsK/JMxzWzvog=,iv:dhhFiPVrK8zssReYxmyFro6CivDde1OmHr6rls4GtQE=,tag:Qp1Q6Or+xbfj2eMoyn+ozQ==,type:str]
    SECRET_DOMAIN_2: ENC[AES256_GCM,data:T3KZTY0wpgUnopWU/w==,iv:kAQ/iyON9qpAeB6YhTCC04KbPTPgdOo2+9ehPFmoCLk=,tag:n/gYr1AcHvpL80UFfs/mfQ==,type:str]
    SECRET_NFS_ZFS1_SERVER: ENC[AES256_GCM,data:ag9C4aO3B1ajmiM=,iv:BrfSrojyK+xlzDyxgxJhOMlkZKTXuzArk375HCTX9ow=,tag:ivEeYAJQoVAOva1a3GJUPw==,type:str]
    SECRET_NFS_ZFS1_PATH: ENC[AES256_GCM,data:jQjkUIqOE1nQcZXeKhtB558xfW/qPcCBxHMg,iv:UsgUU4bWk6B9vXx1nxlHQIEXelz/kFheTVyjxkLExAE=,tag:BPrO4O8iz2m7/8YQoVLFTw==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:uMpU/ITzuRXeLPKHhq4TuntpjTGX7Gev0JYMbdg2sxU=,iv:Se0q0flaw3D/G230S/IuIT+TvAU0oM+ykz/3JwvrlDE=,tag:fixbUmU7abZTYirPNxFTAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc09qa3FmU3EvQVcwOEUy
            L1kyT1dqYmsyV2dEOXFIdnAvN1dZdDFlWDBrCk9ZWmtIU1FlNG1OR1krelEvcEVz
            Y2xuNDFVQ21mVlZiUGFHcnNaa2FIeEUKLS0tIERNTGw3VXA4RGV0K2JNVzZPYzdI
            anY3MkllY0UrY1Rzei9LUDhDRXV4NjQK45OqcE/ZUi85FWLj82gDPv8Xcy83glWy
            mIG/TXZftDjTL60BfQcFt2FDZK+yxJ+rrFhLDLNwDzH5+N9f3pHfuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T03:55:21Z"
    mac: ENC[AES256_GCM,data:3CHb3OfwzVzaaRW5HjcpS5z/qUVj0DC/Zxp5xdfzZrsabnM94LNpvFM7UBLaQs0McTKiXzmUve0TNwWx+AfEvhwDufir6x468vxHp8GM3mRQwjK20zJQ6TtEMn8BA75hUGxrwzPCXHHwQPw5uZXqmdadHt1ydpq4IwT9HObj7wA=,iv:0xY/o9aCbbSB7fcWoddqc3svR2GkYafXNWAg8Hhq/kQ=,tag:5k4xWUZxGeZNhCldtnNHzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
