---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentication
resources:
  - ./secrets.sops.yaml
  - ./secret-configs.sops.yaml
  - ./helmrelease.yaml
  - ./gatus.yaml
